Metrics/AbcSize:
  Max: 21.79
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'route']
Metrics/MethodLength:
  Max: 13
Minitest:
  Include:
    - '**/*_spec.rb'
Style/Documentation:
  Enabled: false
