Metrics/AbcSize:
  Max: 25.04
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'route']
Metrics/MethodLength:
  Max: 13
Minitest:
  Include:
    - '**/*_spec.rb'
Style/Documentation:
  Enabled: false
