require:
  - rubocop-performance
  - rubocop-sequel

AllCops:
  TargetRubyVersion: 2.6

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['dataset_module', 'describe', 'helpers']

Metrics/AbcSize:
  Max: 20.62

Metrics/MethodLength:
  Max: 13
