dist: trusty
sudo: false

language: ruby
rvm:
  - 2.5

addons:
  postgresql: 10
before_install:
  - "psql -c 'create database frankfurter_test;' -U postgres"

services:
  - docker

bundler_args: "--without development test"
env:
  - APP_ENV=test

deploy:
  provider: script
  script: bash bin/docker_push
  on:
    branch: master
