version: '3'
services:
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    container_name: web
    command: bundle exec unicorn -c config/unicorn.rb
    entrypoint: bin/wait-for-it.sh db:5432 -s --
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
    expose:
      - '8080'
    links:
      - db
volumes:
  data:
