version: '3'
services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
  web:
    build: .
    command: unicorn -c ./config/unicorn.rb
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
    entrypoint: ./wait-for-it.sh db:5432 -s --
    expose:
      - '8080'
    links:
      - db
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  data:
