version: '2'
services:
  db:
    image: postgres
  memcache:
    image: memcached
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      RACK_ENV: production
      DATABASE_URL: postgres://postgres@db/postgres
      MEMCACHE_SERVERS: memcache
    links:
      - db
      - memcache
