version: '3'
services:
  web:
    build: .
    environment:
      APP_ENV: development
      VIRTUAL_HOST: localhost
    ports:
      - "8080:8080"
  scheduler:
    build: .
    environment:
      APP_ENV: development
